name: E2E Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            app/app.go
            app/upgrades/*
            go.mod
            go.sum
            tests/e2e/*
      - name: Configure Git for HTTPS authentication
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global credential.helper store
          git remote set-url origin https://github.com/evmos/evmos.git
          git config --global --add url."git@github.com/".insteadOf "https://github.com/"
      - name: Test E2E
        run: |
          go env -w GOPRIVATE=github.com/evmos/*
          go env
          go get github.com/evmos/precompiles
          make test-e2e
        if: env.GIT_DIFF

